name: Get Train

on:
  schedule:
    - cron: "9 4 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@main
        with:
          persist-credentials: true

      - name: Set timezone to Asia/Shanghai
        run: |
          sudo timedatectl set-timezone Asia/Shanghai

      - name: Run
        run: |
          chmod +x ./get_train
          ./get_train

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          COMMIT_TIME=$(date +"%Y-%m-%d")

          git add .
          git commit -m "${COMMIT_TIME}" || echo "Nothing to commit"
          git push
